### ISSUE TITLE
Update to Docusaurus v2

### ISSUE THREAD

**Issue by HonkingGoose** [happo/docs#25]
## Intro

This repository still uses Docusaurus v1 to generate the documentation site.
Docusaurus v1 is no longer getting many updates, as the developers are working on the replacement: Docusaurus v2.

## Proposal

I think there are two good options to improve the documentation site:

- Update to Docusaurus v2
- Switch to MkDocs + Material for MkDocs

I have experience with both of these tools. Both tools offer:

- Site preview
- Search (built-in with MkDocs for Material, needs manual work on Docusaurus v2)
- Good default looks
- Edit button that links to the source files (so that readers can suggest changes)
- Can host via GitHub Pages
- Site customization (colors)

### Update to Docusaurus v2

I tried the automatic migration [^automated-migration], and got parts of the site working, but important things are broken:

- Footer styling
- No homepage
- Custom CSS broken
- Probably more things that I'm forgetting to list

The maintainers of Docusaurus offer to help migrate anyone on Docusaurus v1. [^migration-help] So if you want to update to v2, I'd let them help you.

With Docusaurus v2 it's easy to get a search bar working by integrating Algolia DocSearch [^docsearch-oss] - free for OSS documentation sites - into Docusaurus.[^docusaurus-search]

### Switch to MkDocs + Material for MkDocs

The benefit of MkDocs + Material for MkDocs above Docusaurus v2:

- Better documentation/manual
- Page search works out of the box, no integrations needed
- Stable tooling, no beta versions

## What would I do?

This repository does not get many commits, as you're probably focusing on your core product (Happo). So any documentation tooling needs to be easy to use, and easy to maintain.

I'd switch to MkDocs + Material for MkDocs as it's easy to use, does not require any manual work to setup search, and the project is well maintained and stable. The features are well documented and come with handy before/after pictures, so you can see what the feature does right in the docs.

## Tooling manuals

[Docusaurus v2 docs](https://docusaurus.io/)
[Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)
[MkDocs](https://www.mkdocs.org/)

## Footnotes

[^migration-help]: https://docusaurus.io/docs/migration#support
[^automated-migration]: https://docusaurus.io/docs/migration/automated
[^docusaurus-search]: https://docusaurus.io/docs/search#using-algolia-docsearch
[^docsearch-oss]: https://www.algolia.com/for-open-source/

**Comment by trotzig** [comment]
Hi @HonkingGoose! Wow, thanks for taking the time to do this investigation! I didn't know docusaurus v2 had been released -- but as you mention, we don't spend too much time in this repo. :)

I've been happy with docusaurus and even though MKDocs looks good, I'd like to stay away from switching to a different tool at this time. Migrating to v2 isn't in our immediate backlog though so any help here would be deeply appreciated! As far as search goes, I think google's index is taking is quite far and I'd like to stay away from third party tools like Algolia,. 

I like the edit button that links to the source file on github -- that's something I've been meaning to add myself. 

Site previews would be nice to have on each PR, but running the site locally takes us a long way as well. I'm assuming this would mean each PR would have a link to a preview of the website, right?

**Comment by HonkingGoose** [comment]
> Hi @HonkingGoose! Wow, thanks for taking the time to do this investigation! I didn't know docusaurus v2 had been released -- but as you mention, we don't spend too much time in this repo. :)

You're welcome! The maintainers of Docusaurus v2 do think it's ready for production use now already, so you don't have to wait until they have their first official stable v2 release.

> I've been happy with docusaurus and even though MKDocs looks good, I'd like to stay away from switching to a different tool at this time. Migrating to v2 isn't in our immediate backlog though so any help here would be deeply appreciated!

Fair enough. I just wanted to mention MkDocs, as I really like it. 😄 

I'm not familiar with customizing Docusaurus, so I'll let the maintainer help you with getting your customization working again on `v2`. 😉

>  As far as search goes, I think google's index is taking is quite far and I'd like to stay away from third party tools like Algolia,.

Setting up search can be a hassle, that's why I suggested Material for MkDocs, it comes with search built-in.

But if you feel that your users are happy googling it, then you don't need to bother with search at all, which is less work. 😄 

> I like the edit button that links to the source file on github -- that's something I've been meaning to add myself.

Here's the [Docusaurus `v1` `edit_url` docs](https://v1.docusaurus.io/docs/en/site-config.html#editurl-string) you need to get that edit button. 😉 

> Site previews would be nice to have on each PR, but running the site locally takes us a long way as well. I'm assuming this would mean each PR would have a link to a preview of the website, right?

I'm sorry for the confusion, when I said "site preview" I meant that you can easily run a development server locally. 🙈 

If you want a site preview in the PR, you can get that when deploying with Vercel/Netlify, they add a link to the PR where you can preview the PR and click around on the "preview deployment". 😉 I don't think GitHub Pages offers a deployment preview in the PR yet, that would be really cool... 🤯

**Comment by HonkingGoose** [comment]
> Migrating to v2 isn't in our immediate backlog though so any help here would be deeply appreciated!

When you're ready to work on the migration to Docusaurus `v2` ask `@slorber` if they want to help you.

**Comment by trotzig** [comment]
Will do!

**Comment by HonkingGoose** [comment]
Docusaurus v2 was officially released a while ago. [^blog] 🥳 They have docs to help you migrate from v1 to v2. [^docs-migrate] 

One of the maintainers of Docusaurus v2 offers to help review a migration PR, quote from the migration docs:

> Feel free to tag [`@slorber`](https://github.com/slorber) in any migration PRs if you would like us to have a look.

[^blog]: https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0
[^docs-migrate]: https://docusaurus.io/docs/migration
